// Generated by gencpp from file storm_gimbal/gimbal.msg
// DO NOT EDIT!


#ifndef STORM_GIMBAL_MESSAGE_GIMBAL_H
#define STORM_GIMBAL_MESSAGE_GIMBAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace storm_gimbal
{
template <class ContainerAllocator>
struct gimbal_
{
  typedef gimbal_<ContainerAllocator> Type;

  gimbal_()
    : roll(0.0)
    , pitch(0.0)  {
    }
  gimbal_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)  {
  (void)_alloc;
    }



   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;





  typedef boost::shared_ptr< ::storm_gimbal::gimbal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::storm_gimbal::gimbal_<ContainerAllocator> const> ConstPtr;

}; // struct gimbal_

typedef ::storm_gimbal::gimbal_<std::allocator<void> > gimbal;

typedef boost::shared_ptr< ::storm_gimbal::gimbal > gimbalPtr;
typedef boost::shared_ptr< ::storm_gimbal::gimbal const> gimbalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::storm_gimbal::gimbal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::storm_gimbal::gimbal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::storm_gimbal::gimbal_<ContainerAllocator1> & lhs, const ::storm_gimbal::gimbal_<ContainerAllocator2> & rhs)
{
  return lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::storm_gimbal::gimbal_<ContainerAllocator1> & lhs, const ::storm_gimbal::gimbal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace storm_gimbal

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::storm_gimbal::gimbal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::storm_gimbal::gimbal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::storm_gimbal::gimbal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::storm_gimbal::gimbal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::storm_gimbal::gimbal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::storm_gimbal::gimbal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::storm_gimbal::gimbal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f5aa311af37faead3f9e90f420c9603";
  }

  static const char* value(const ::storm_gimbal::gimbal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f5aa311af37faeaULL;
  static const uint64_t static_value2 = 0xd3f9e90f420c9603ULL;
};

template<class ContainerAllocator>
struct DataType< ::storm_gimbal::gimbal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "storm_gimbal/gimbal";
  }

  static const char* value(const ::storm_gimbal::gimbal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::storm_gimbal::gimbal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 roll\n"
"float64 pitch\n"
;
  }

  static const char* value(const ::storm_gimbal::gimbal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::storm_gimbal::gimbal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gimbal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::storm_gimbal::gimbal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::storm_gimbal::gimbal_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STORM_GIMBAL_MESSAGE_GIMBAL_H
