// Generated by gencpp from file ros_gimbal/gimbal.msg
// DO NOT EDIT!


#ifndef ROS_GIMBAL_MESSAGE_GIMBAL_H
#define ROS_GIMBAL_MESSAGE_GIMBAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ros_gimbal
{
template <class ContainerAllocator>
struct gimbal_
{
  typedef gimbal_<ContainerAllocator> Type;

  gimbal_()
    : header()
    , roll(0.0)
    , pitch(0.0)  {
    }
  gimbal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , roll(0.0)
    , pitch(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;





  typedef boost::shared_ptr< ::ros_gimbal::gimbal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_gimbal::gimbal_<ContainerAllocator> const> ConstPtr;

}; // struct gimbal_

typedef ::ros_gimbal::gimbal_<std::allocator<void> > gimbal;

typedef boost::shared_ptr< ::ros_gimbal::gimbal > gimbalPtr;
typedef boost::shared_ptr< ::ros_gimbal::gimbal const> gimbalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_gimbal::gimbal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_gimbal::gimbal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_gimbal::gimbal_<ContainerAllocator1> & lhs, const ::ros_gimbal::gimbal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_gimbal::gimbal_<ContainerAllocator1> & lhs, const ::ros_gimbal::gimbal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_gimbal

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_gimbal::gimbal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_gimbal::gimbal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_gimbal::gimbal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_gimbal::gimbal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_gimbal::gimbal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_gimbal::gimbal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_gimbal::gimbal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac1faa2f4f533aa88a90417967a8db18";
  }

  static const char* value(const ::ros_gimbal::gimbal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac1faa2f4f533aa8ULL;
  static const uint64_t static_value2 = 0x8a90417967a8db18ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_gimbal::gimbal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_gimbal/gimbal";
  }

  static const char* value(const ::ros_gimbal::gimbal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_gimbal::gimbal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 roll\n"
"float64 pitch\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ros_gimbal::gimbal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_gimbal::gimbal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.roll);
      stream.next(m.pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gimbal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_gimbal::gimbal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_gimbal::gimbal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_GIMBAL_MESSAGE_GIMBAL_H
